################################################################################
#                  OneBranch Pipelines - PR Build                              #
################################################################################
#                                                                              #
# This pipeline is for validation of pull requests. Useful links:              #
#                                                                              #
#   https://www.osgwiki.com/wiki/Windows_Undocked_Template                     #
#   https://aka.ms/obpipelines                                                 #
#   https://aka.ms/obpipelines/yaml/schema                                     #
#   https://aka.ms/obpipelines/tasks                                           #
#   https://aka.ms/onebranchsup                                                #
#                                                                              #
################################################################################

trigger: none # https://aka.ms/obpipelines/triggers

pr:
- main
- release/*
- msrc/*

variables:
  # https://aka.ms/obpipelines/containers
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest'

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
  - repository: undocked
    type: github
    name: microsoft/undocked
    ref: refs/heads/main
    endpoint: Undocked GitHub

extends:
  # https://aka.ms/obpipelines/templates
  template: v2/Microsoft.NonOfficial.yml@templates
  parameters:
    platform:
      name: 'windows_undocked'
    featureFlags:
      WindowsHostVersion: '1ESWindows2022'
    stages:
    - stage: Build
      jobs:
      - template: onebranch/v1/build.yml@undocked
        parameters:
          sln: fnmp.sln
          platform: 'x64,arm64'
          nugetConfigPath: './src/nuget.config'
          outDir: 'artifacts'
