//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

#pragma once

EXTERN_C_START

#define FNLWFAPI_STATUS HRESULT
#define FNLWFAPI_FAILED(X) FAILED(X)
#define FNLWFAPI_SUCCEEDED(X) SUCCEEDED(X)

#define FNLWFAPI_STATUS_NOT_FOUND       HRESULT_FROM_WIN32(ERROR_NOT_FOUND)
#define FNLWFAPI_STATUS_MORE_DATA       HRESULT_FROM_WIN32(ERROR_MORE_DATA)
#define FNLWFAPI_STATUS_NOT_READY       HRESULT_FROM_WIN32(ERROR_NOT_READY)

EXTERN_C_END
